/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <time.h>
#include <android/log.h>
#include <android/bitmap.h>

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

#define  LOG_TAG    "libimageprocessing"
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)
#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)

/* Header for class com_example_user_ndk_pep_MainActivity */

#ifndef _Included_com_example_user_ndk_pep_MainActivity
#define _Included_com_example_user_ndk_pep_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_user_ndk_pep_MainActivity_MODE_PRIVATE
#define com_example_user_ndk_pep_MainActivity_MODE_PRIVATE 0L
#undef com_example_user_ndk_pep_MainActivity_MODE_WORLD_READABLE
#define com_example_user_ndk_pep_MainActivity_MODE_WORLD_READABLE 1L
#undef com_example_user_ndk_pep_MainActivity_MODE_WORLD_WRITEABLE
#define com_example_user_ndk_pep_MainActivity_MODE_WORLD_WRITEABLE 2L
#undef com_example_user_ndk_pep_MainActivity_MODE_APPEND
#define com_example_user_ndk_pep_MainActivity_MODE_APPEND 32768L
#undef com_example_user_ndk_pep_MainActivity_MODE_MULTI_PROCESS
#define com_example_user_ndk_pep_MainActivity_MODE_MULTI_PROCESS 4L
#undef com_example_user_ndk_pep_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_example_user_ndk_pep_MainActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_example_user_ndk_pep_MainActivity_BIND_AUTO_CREATE
#define com_example_user_ndk_pep_MainActivity_BIND_AUTO_CREATE 1L
#undef com_example_user_ndk_pep_MainActivity_BIND_DEBUG_UNBIND
#define com_example_user_ndk_pep_MainActivity_BIND_DEBUG_UNBIND 2L
#undef com_example_user_ndk_pep_MainActivity_BIND_NOT_FOREGROUND
#define com_example_user_ndk_pep_MainActivity_BIND_NOT_FOREGROUND 4L
#undef com_example_user_ndk_pep_MainActivity_BIND_ABOVE_CLIENT
#define com_example_user_ndk_pep_MainActivity_BIND_ABOVE_CLIENT 8L
#undef com_example_user_ndk_pep_MainActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_example_user_ndk_pep_MainActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_example_user_ndk_pep_MainActivity_BIND_WAIVE_PRIORITY
#define com_example_user_ndk_pep_MainActivity_BIND_WAIVE_PRIORITY 32L
#undef com_example_user_ndk_pep_MainActivity_BIND_IMPORTANT
#define com_example_user_ndk_pep_MainActivity_BIND_IMPORTANT 64L
#undef com_example_user_ndk_pep_MainActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_example_user_ndk_pep_MainActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_example_user_ndk_pep_MainActivity_CONTEXT_INCLUDE_CODE
#define com_example_user_ndk_pep_MainActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_example_user_ndk_pep_MainActivity_CONTEXT_IGNORE_SECURITY
#define com_example_user_ndk_pep_MainActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_example_user_ndk_pep_MainActivity_CONTEXT_RESTRICTED
#define com_example_user_ndk_pep_MainActivity_CONTEXT_RESTRICTED 4L
#undef com_example_user_ndk_pep_MainActivity_RESULT_CANCELED
#define com_example_user_ndk_pep_MainActivity_RESULT_CANCELED 0L
#undef com_example_user_ndk_pep_MainActivity_RESULT_OK
#define com_example_user_ndk_pep_MainActivity_RESULT_OK -1L
#undef com_example_user_ndk_pep_MainActivity_RESULT_FIRST_USER
#define com_example_user_ndk_pep_MainActivity_RESULT_FIRST_USER 1L
#undef com_example_user_ndk_pep_MainActivity_DEFAULT_KEYS_DISABLE
#define com_example_user_ndk_pep_MainActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_example_user_ndk_pep_MainActivity_DEFAULT_KEYS_DIALER
#define com_example_user_ndk_pep_MainActivity_DEFAULT_KEYS_DIALER 1L
#undef com_example_user_ndk_pep_MainActivity_DEFAULT_KEYS_SHORTCUT
#define com_example_user_ndk_pep_MainActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_example_user_ndk_pep_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_example_user_ndk_pep_MainActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_example_user_ndk_pep_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_example_user_ndk_pep_MainActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef com_example_user_ndk_pep_MainActivity_HONEYCOMB
#define com_example_user_ndk_pep_MainActivity_HONEYCOMB 11L
#undef com_example_user_ndk_pep_MainActivity_MSG_REALLY_STOPPED
#define com_example_user_ndk_pep_MainActivity_MSG_REALLY_STOPPED 1L
#undef com_example_user_ndk_pep_MainActivity_MSG_RESUME_PENDING
#define com_example_user_ndk_pep_MainActivity_MSG_RESUME_PENDING 2L
/*
 * Class:     com_example_user_ndk_pep_MainActivity
 * Method:    changeBrightness
 * Signature: ()Ljava/lang/String;
 */

//JNIEXPORT void JNICALL
JNIEXPORT void Java_com_example_user_ndk_1pep_MainActivity_changeBrightness(JNIEnv *env,
                                                                            jobject obj,
                                                                            jobject bitmap,
                                                                            jboolean makeNegative,
                                                                            jfloat brightnessValue,
                                                                            jbooleanArray rgb_exist);

static void brightness(AndroidBitmapInfo *info, void *pixels, float brightnessValue,
                       jboolean r_bool, jboolean g_bool, jboolean b_bool);

static void makeImageNegative(AndroidBitmapInfo *info, void *pixels, float brightnessValue,
                              jboolean r_colour, jboolean g_colour, jboolean b_colour);

static int rgb_clamp(int value);

#ifdef __cplusplus
}
#endif
#endif
